### ISSUE TITLE
TypeError: db.findall is not a function

### ISSUE THREAD

**Issue by matthiasmoier** [kosamari/who-pays-tech-speakers#40]
When you click on one of the links at the bottom of the page ([JSON](http://whopays.techspeakers.info/data.json), [CSV](http://whopays.techspeakers.info/data.csv), [data table](http://whopays.techspeakers.info/lab/datatable)), the page crashes and the following error shows:

`TypeError: db.findall is not a function at /opt/who-pays-tech-speakers/app.js:109:6 at callbacks (/opt/who-pays-tech-speakers/node_modules/express/lib/router/index.js:164:37) at param (/opt/who-pays-tech-speakers/node_modules/express/lib/router/index.js:138:11) at pass (/opt/who-pays-tech-speakers/node_modules/express/lib/router/index.js:145:5) at Router._dispatch (/opt/who-pays-tech-speakers/node_modules/express/lib/router/index.js:173:5) at Object.router (/opt/who-pays-tech-speakers/node_modules/express/lib/router/index.js:33:10) at next (/opt/who-pays-tech-speakers/node_modules/express/node_modules/connect/lib/proto.js:193:15) at resume (/opt/who-pays-tech-speakers/node_modules/express/node_modules/connect/lib/middleware/static.js:65:7) at SendStream.error (/opt/who-pays-tech-speakers/node_modules/express/node_modules/connect/lib/middleware/static.js:80:37) at emitOne (events.js:90:13)`

**Comment by matthiasmoier** [comment]
Any update on this?

**Comment by Talbot3** [comment]
I am also have same problem.did you solve it?
```javascript
    var db = this.db;
    db.finAll().then(function (result) {
        cb(null, result);
    }).catch(function (err) {
        cb(err);
    });
```

```
/home/crazy/Proj/people_counting_statistics/service/MonitorDB.js:72
    db.finAll().then(function (result) {
       ^

TypeError: db.finAll is not a function
    at Monitor.getIpList [as ipList] (/home/crazy/Proj/people_counting_statistics/service/MonitorDB.js:72:8)
    at Object.listMonitorIp (/home/crazy/Proj/people_counting_statistics/controller/MonitorController.js:53:19)
    at module.exports (/home/crazy/Proj/people_counting_statistics/controller/MonitorWorkerComtroller.js:29:23)
    at module.exports (/home/crazy/Proj/people_counting_statistics/controller/Genesis.js:24:54)
    at Object.<anonymous> (/home/crazy/Proj/people_counting_statistics/bin/www:28:37)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

**Comment by rootwork** [comment]
I'm a sometimes-conference organizer, and having the data table available to show to fellow organizers about why we should pay speakers has been really helpful. Disappointed to see that it's not available. @kosamari any chance it could be restored? Even if the only version available is out of date, it's still really useful data!

**Comment by kosamari** [comment]
Hey all - sorry for not keeping up with issues.

Just moved database off of my server & moved to firebase. Things should get a lot stable 💯
